# Use Nginx to serve static files
FROM nginx:alpine

# Copy all templates to the default Nginx public folder
COPY ./templates /usr/share/nginx/html

# Copy custom nginx configuration
COPY ./services/gateway/frontend.conf /etc/nginx/conf.d/default.conf

# Copy any static files if they exist
# COPY ./static /usr/share/nginx/html/static

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
