# Generated by Django 5.1 on 2026-04-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20260417_1434'),
    ]

    operations = [
    ]
