# Generated by Django 5.1 on 2026-04-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_job_title_user_location_user_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('milestone', 'Milestone'), ('community', 'Community'), ('creative', 'Creative'), ('engagement', 'Engagement'), ('professional', 'Professional')], default='milestone', max_length=20),
        ),
        migrations.AddField(
            model_name='achievement',
            name='is_rare',
            field=models.BooleanField(default=False, help_text='Rare achievements are highlighted'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='unlock_threshold',
            field=models.PositiveIntegerField(default=1, help_text='Threshold for unlocking this achievement'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Whether the achievement is fully completed'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='Current progress towards achievement'),
        ),
    ]
