# Generated by Django 5.1 on 2026-04-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_achievement_category_achievement_is_rare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_thumbnail',
            field=models.ImageField(blank=True, help_text='Processed thumbnail for profile display', null=True, upload_to='avatars/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='High-resolution avatar image', null=True, upload_to='avatars/'),
        ),
    ]
