# Generated by Django 5.1 on 2026-04-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display name for profile (different from username)', max_length=100, null=True),
        ),
    ]
