upstream user_service {
    server user-service:8000;
}

upstream artwork_service {
    server artwork-service:8000;
}

upstream interaction_service {
    server interaction-service:8000;
}

upstream notification_service {
    server notification-service:8000;
}

upstream frontend {
    server frontend:80;
}

server {
    listen 80;

    location /api/users/ {
        proxy_pass http://user_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Authorization $http_authorization;
    }

    location /api/artworks/ {
        proxy_pass http://artwork_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Authorization $http_authorization;
    }

    location /api/interactions/ {
        proxy_pass http://interaction_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Authorization $http_authorization;
    }

    location /api/notifications/ {
        proxy_pass http://notification_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Authorization $http_authorization;
    }

    location /media/ {
        alias /usr/share/nginx/html/media/;
        add_header 'Access-Control-Allow-Origin' '*';
        autoindex on;
    }

    location / {
        proxy_pass http://frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Ignore Vite dev requests from Trae/Browser
    location /@vite/ {
        return 404;
    }
}
