# Generated by Django 5.1 on 2026-04-17 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
    ]
