# Generated by Django 5.1 on 2026-04-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_tag_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='artworks',
        ),
        migrations.AddField(
            model_name='artwork',
            name='likes',
            field=models.PositiveIntegerField(default=0, help_text='Number of likes for engagement'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Artwork tags for categorization', related_name='artworks', to='artworks.tag'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Generated thumbnail for gallery display', null=True, upload_to='artworks/thumbnails/'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Number of views for analytics'),
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#007bff', help_text='Tag color for UI display', max_length=7),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed artwork description', null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(help_text='High-quality artwork image', upload_to='artworks/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(help_text='Artwork title', max_length=255),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='user_id',
            field=models.IntegerField(help_text='User ID from User Service'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Tag creation timestamp'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Unique tag name', max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['user_id'], name='artworks_ar_user_id_13ba96_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['created_at'], name='artworks_ar_created_e19a9e_idx'),
        ),
    ]
